sudo: required

language: node_js

before_install:
  - chmod +x ./ci/server.sh
  - chmod +x ./ci/client.sh

services:
  - docker

script:
  - ./ci/server.sh
  - ./ci/client.sh

after_success:
  - ./ci/upload.sh

