sudo: required

language: node_js

node_js:
  - "iojs"
  - "7"

before_install:
  - chmod +x ./ci/server.sh
  - chmod +x ./ci/client.sh

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./ci/server.sh
  - ./ci/client.sh

after_success:
  - ./ci/upload.sh

